version: '3'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg15-latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/home/postgres/pgdata/data
    ports:
      - "5432:5432"

  pulsar:
    image: apachepulsar/pulsar:2.10.2
    command: "bin/pulsar standalone"
    ports:
        - '7128:8080'
        - '6650:6650'
    volumes:
        - pulsar_data:/pulsar/data
        - pulsar_conf:/pulsar/conf

  debezium:
    image: debezium/server
    restart: on-failure
    links:
        - "timescaledb"
        - "pulsar"
    ports:
        - '7080:8080'
    volumes:
        - '$PWD/debezium:/debezium/conf'
        - debezium_data:/debezium/data
    depends_on:
      - timescaledb

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"
    ports:
      - 16686:16686 # dashboard
      - 16685:16685
      - 14250:14250
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http

volumes:
  postgres:
  debezium_data:
  pulsar_data:
  pulsar_conf: